controller:
  admin: 
    username: "admin"
    password: "admin123"
  serviceType: LoadBalancer
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
persistence:
  enabled: true
  size: 10Gi
