apiVersion: v1
kind: Service
metadata:
  name: transcriber-frontend
spec:
  type: LoadBalancer
  selector:
    app: transcriber-frontend
  ports:
  - protocol: TCP
    port: 3000       # External port
    targetPort: 3000 # Container port
